### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by maximpetrov** [Phambanam/Grep#1]
1. Вместо `setCmd*` методов лучше задавать эти поля через конструктор.
1. Конструктор `Grep` и метод `find` следует сделать `public`.
1. В режиме поиска по регулярному выражению так же не обязательно вся строка должна целиком подходить под это регулярное выражение, достаточно соответствия части строки.
1. Вы не учитываете, что в режиме поиска по слову это слово может содержать спецсимволы регулярных выражений.
1. Работать с файлом лучше через try-with-resources.

**Comment by Phambanam** [comment]
я уже исправлял
Пожалуйста проверте мне!

**Comment by maximpetrov** [comment]
1. Повторюсь, boolean поля тоже следует задавать через конструктор.
1. Вместо того, чтобы добавлять `.*` в начале и конце, можно воспользоваться `find()` вместо `matches()`.
1. Нет необходимости экранировать каждый символ руками, можно просто всю строку, которую нужно экранировать между `\Q` и `\E`. А ещё проще и лучше использовать `Pattern.quote()`, который сделает то же самое.
1. try-with-resources оформляется вот [так](https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html). А исключения внутри `find()` не стоит ловить, тогда Вы скроете ошибку от вышестоящей функции.
1. Если утилита завершается с ошибкой, то лучше выходить через `System.exit()` с ненулевым кодом.

**Comment by Phambanam** [comment]
я не понимаю  второй , что мне надо делать.

**Comment by maximpetrov** [comment]
Вы делаете из шаблона для поиска `"test"` шаблон `".*test.*"`, чтобы подходила вся строка, а можно этого не делать, а воспользоваться `find()` вместо `matches()`, который не требует, чтобы строка подходила под шаблон целиком, достаточно чтобы подходила какая-то её часть.

**Comment by Phambanam** [comment]
извините
второй я понял,не понял третий

**Comment by maximpetrov** [comment]
Вместо того, чтобы из экранировать каждый символ (`"(12{3})"` -> `"\(12\{3\}\)"`), можно экранировать строку целиком (`"(12{3})"` -> `"\Q(12{3})\E"`). А ещё проще и правильнее будет сделать `Pattern.quote("(12{3})")`.

**Comment by maximpetrov** [comment]
Причём `Pattern.quote` правильнее тем, что он правильно обработает ситуацию, когда `"\E"`, встретится в исходной строке.

**Comment by Phambanam** [comment]
спасибо ,я понял

**Comment by Phambanam** [comment]
Пожалуйста , скажите мне, что надо делать задание 3?

**Comment by maximpetrov** [comment]
3 задание - приложение с графическим интерфейсом. Можно придумать задание самостоятельно или выбрать из следующего списка: шашки (русские или английские), реверси, рэндзю, сапёр на шестиугольном поле, симулятор планетной системы, нарды (длинные или короткие). Для игр не требуется компьютерный игрок, только режим игрок против игрока. Если будете придумывать своё задание, то его сложность должна быть не ниже, чем у приведённых вариантов. В любом случае, когда выберете или придумаете себе задание, напишите мне об этом (лучше на email).

**Comment by Phambanam** [comment]
Это задание я сдал или Что мне еще надо делать ?

Vào Th 2, 20 thg 4, 2020 lúc 02:45 Maxim Petrov <notifications@github.com>
đã viết:

**Comment by maximpetrov** [comment]
Да, это задание принято

**Comment by Phambanam** [comment]
Здравствуйте!
Я Фам Ба Нам
3530901/90001
https://github.com/Phambanam/Zadanie3
Это проект задание3
Я написал игру в шашки для двух игроков.
Правила следующие:
Я написал игру в шашки для двух игроков.
Я выполню еще несколько функций для этого
Правила следующие:
How to Play Caro Playing Caro is pretty straightforward. It is played using
the X and O symbol. The player representing the “X” symbol gets to take the
first turn followed by the player representing the “O” symbol. Players take
turns placing their symbol on an open intersection on the board. It is very
much a game of strategy, as players have to race to create an unbroken row
of five symbols while blocking their opponent to prevent them from creating
five in a row. The player that manages to create five in a row first wins
the round. The row can be horizontal, vertical, or diagonal as long as it
is unbroken.

Vào CN, 26 thg 4, 2020 vào lúc 01:34 Maxim Petrov <
notifications@github.com> đã viết:
